import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchProducts } from './ProductAPI';

const initialState = {
  products: [],
  status: 'idle',
};

export const fetchAllProdctsAsync = createAsyncThunk(
  'product/fetchProducts',
  async () => {
    const response = await fetchProducts();
    // The value we return becomes the `fulfilled` action payload
    return response.data;
  }
);

export const productListSlice = createSlice({
  name: 'product',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAllProdctsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchAllProdctsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.products = action.payload;
      });
  },
});

export default productListSlice.reducer;
